### PR TITLE
Optimise gradient

### PR DESCRIPTION
**Pull request by CyprienBosserelle**
# Optimising gradient and gradient-halo

There is a new test to confirm the validity of the new gradient and gradient halo the speed gain.
The new scheme is about 1.8x faster than original which should make the whole simulation 1.15x faster

This makes the model 22% faster than the current dev branch

- [x] Make New Halo script
- [x] Make new Gradient scheme
- [x] Write test for new halo scheme ~~including speed test~~
- [x] write test for new gradient scheme including speed test
- [x] Fix any bugs in refine linear and conserve elevation that might cause instability at wet dry interface
- [x] add some documentation
- [x] double check gpu vs cpu
- [x] Add test to CI
- [x] Implement wet/dry instability fix for when conserve elevation is not requested
- [x] Test wet/dry instability implementation

### CODE REVIEW

**Comment by CyprienBosserelle** [comment]
Need to write a new test for the halo to verify where the bug is and once fixed whether this new scheme is worth it

**Comment by CyprienBosserelle** [comment]
The new halo scheme does not work and I'm not too sure why. a day of work didn't get me very far. I think I'm happy to drop that part and merge what I have done to move this along and possibly move on to more important problems.

**Comment by CyprienBosserelle** [comment]
# Note for the review
This is good to merge after review. There is a lot of changes done here. I'm not expecting a full review of the code but a couple of manual test to see if the model does go a bit faster and give similar results (I do not expect exact same results because of bug fixes).

I 've run a few test using Waikanae topo and will do a few more today.

**Comment by CyprienBosserelle** [comment]
# There is another thing that could be done here but i'm not sure the consequence. 
All of the instabilities (when not using Conserve Elevation) are because of the wet/dry front and varying resolution don't mix well. The solution to that issue in "Conserve elevation"  uses a direct injection of values from the coarse wet cell for the halo rather than what come from refine linear. while "Conserv elevation" also does other things maybe we can use that prolongation even when not requesting conserve elevation. that would in effect only affect the cells at the wet/dry interface. The only issue would be that those cells do not conserve volume. does it mater so much?

- [ ] Implement idea above
- [ ] Test with ROG problem
- [ ] Compare with Dev branch to see how bad it is.

**Comment by CyprienBosserelle** [comment]
# Revert prolongation from conserve elevation when cells are fully wet? 
Straight injection from Prolongation when neighbouring cell is dry affects the value of h, zs and zb. Also this action doesn't affect dzbdx. is that ok?
The changes to zb should probably reverted at the end of the step. no?

**Comment by CyprienBosserelle** [comment]
# Preformed a test to see the influence/impact of switching on/off the :
dhdx[halo] = T(0.0);
dzsdx[halo] = T(0.0);

in ProlongationElevationGH.
This seem to have little effect.

**Comment by CyprienBosserelle** [comment]
## This merge request does a lot of different things to gradient, halo and Conserve elevation.

### 2 full scale test are needed to compare Dev branch and this branch

- [ ] Rain on grid over Westport or Waikanae
- [ ] Tsunami over Samoa

Once we are happy with the difference it will be ready to merge!

**Comment by CyprienBosserelle** [comment]
## Waikanae Mass conservation test
Waikanae topo with cst rain at 50mm/h for 1 h. using the rainbnd option and wall bnd on all side.
Results are undestinguishable from each other and after 1 hr the model has **100.48%** of the theoretical volume of water in both with and without the wetdryfix.  

For comparison the current **Dev** branch has 100.19% of the theoretical volume. While this is somehow better it does not really undermine the new branch (i.e. the dev branch might get closer to the theory for the wrong raisons), the bugfixes and instability improvement of this branch are totally justified. 

results
|   | % of theoretical volume | runtime |
| ------------- | ------------- | ------------- |
| Wetdry fix  | 100.48%  | 97s  |
| **NO** Wetdryfix  | 100.48%  | 96s  |
| Development  | 100.18%  | 116s  |

**Comment by CyprienBosserelle** [comment]
# Tsumani test results

The impact of the wet/dry fix should be much more obvious in tsunami simulation but here conserve elevation should be used in most tsunami cases.

## No wetdryfix
switching off the wetdryfix causes instability that really have an impact on tsunami wave. Here the instability are clearly visible in the map and in the comparison are seen as 0.01 m waves before the tsunami wave arrive.

image

## Wetdryfix
When using the wetdryfix the instabilities disappear and the solution is smoother.

image

## Comparison
The instabilities are more obvious when we look at a transect diagonally from the plot above. These instabilities have a notable affect the height of the tsunami wave... a lot! This justifies that we should have the wetdryfix switched on by default.

image


## Conserve Elevation
When running tsunami/storm surge simulation without rivers or rain then the conserve elevation should be switched on. This doesn't make a considerable impact on the tsunami wave (see transect above the red and blue line are indistinguishable) I'm not sure why the difference is so small but there is a difference. Below is the difference between the wetdryfix and conservelevation routine. it produces a difference of O(10-5).

 
image

**Review by AliceHarang — APPROVED** [review]
This is an important pull request that fixes wet-dry instabilities and also improve the code and the computational performance.
The new gradient computation has been tested on multi-resolution rain-on-grid test case (Orowaiti area). It shows an improvement of the results and a decrease of 40% of the computational time.

**Pull request merged**
