### PR TITLE
Rain loss - Initial and Continuous loss model

### PR DESCRIPTION
**Pull request by AliceHarang**
This objective is to add a model of Initial and Continuous Loss to the code.
This model aims to add a very basic model of ground infiltration, in order to improve the surface runoff when rain on grid is used.
An initial loss of water is estimated before the runoff begin, then a constant volume of rain, the continuous loss is remove when the runoff occurs. These values are defined, based on the material of the ground, at each cell location.
 
image
_from https://www.mssanz.org.au/modsim2011/I8/elkafagee.pdf_

Discuss:
- It is actually create similarly to the roughness, do we want to be able to add a constant value too?

Steps:
- [x] Create variables: ground water accumulation, IL map, CL map
- [x] Read initial maps of IL - CL
- [x] Write the map in outputs
- [x] Modify the Equations
- [x] Add testcase / validation

### CODE REVIEW

**Comment by AliceHarang** [comment]
Hi, 
Do you think we would need to add the possibility of reading these variables as constant? (next to the actual "map mode")

**Comment by CyprienBosserelle** [comment]
## The new system works great. 
Right now the user has to force the IL and CL as maps an although I though it may be useful to allow a constant value everywhere , I think the way it is now is preferable.  Two things I'd like to see added (I help do that)

- [ ] initialise infiltration to IL where initial h>0.0 so the ocean/estuaries 
- [ ] Need a better output variable name for infiltration

**Comment by CyprienBosserelle** [comment]
Sorry for the pedentic comment about adding a md file for the documentation but I think we need to do that for every PL. That way the documentation doesn't run away from us. I will add that to every pull request for now on....

**Comment by AliceHarang** [comment]
> 

Hi, 
I do agree with the md file, we need to know what is in the code.
For the initial value for the ocean/estuaries, do you want to force it over the user map?
For the moment, if there is a user map, we use it; if there is no IL and CL input, there is no infiltration (everything should have a on/off switch).

Regarding the output var name, I didn't have much inspiration...
(it is the (accumulated) height of water infiltrated through this cell up to this time)

**Comment by CyprienBosserelle** [comment]
I did the initial condition for initial loss  (infiltration = il where h>eps )
I will think of better output name variable and propose a name.

**Comment by AliceHarang** [comment]
Regarding the documentation md file, I made a[ basic word](https://niwa-my.sharepoint.com/:w:/g/personal/alice_harang_niwa_co_nz/EXda8YOd6yRDpP22a6tuPdIBQbEmb76gFnq3H6yM7Crqkw?email=Cyprien.Bosserelle%40niwa.co.nz&e=b51dOV) that I can quickly transform in a md file.

**Comment by AliceHarang** [comment]
I added a md file to explain the model. Do you think it is sufficient? (Can you clarify the figure of expected results?)

**Review by CyprienBosserelle — APPROVED** [review]
Looks good to me!

**Comment by AliceHarang** [comment]
A sanity check on outvars to be sure that the model/options are in phase with the requested outputs.
Done for ic/cl/hgw
Done for datmpdx/datmpdy

**Pull request merged**
