### PR TITLE
Roughness multi input

### PR DESCRIPTION
**Pull request by AliceHarang**
- [x] : Add the possibility to use multiple roughness files
- [x] : Add Test for the  multiple roughness files use
- [x] : Add Test for the multiple bathy files
- [x] : Update the automatic testing

Complementary:
- [x] : Add value input for IL/CL
- [x] : Add test for this value input

### CODE REVIEW

**Comment by AliceHarang** [comment]
After creating the test, I observe a weird behavior when the value is 0 (for bathy and roughness).

**Comment by CyprienBosserelle** [comment]
Would be neat to fix this one as well:
#105

**Comment by AliceHarang** [comment]
I have also finished to add the possibility to have a Continuous Loss and Initial Loss as a constant.

**Comment by CyprienBosserelle** [comment]
I had a quick look again and the way the "NaN" values are removed is the most appropriate way.
There is now a built -in mechanism to remove NAN from input/forcing maps but in the case of vector of map we only want to remove the value from the top map and leave large hole in the data intact for the other maps.

**Comment by CyprienBosserelle** [comment]
if the test succeed please go ahead and merge.
C

**Review by CyprienBosserelle — APPROVED** [review]
All good

**Pull request merged**
